# Data path. adjust them!
common:
    image_file: "/home/felix/Downloads/calib_dataset/mid360/0.jpg"
    pcd_file: "/home/felix/Downloads/calib_dataset/mid360/0.pcd"
    result_file: "/home/felix/catkin_ws/src/livox_camera_calib/result/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [944.4721536811564, 0.0,      643.6506877653053,
                0.0,     941.9027434247072,  357.1776107352139,
                0.0,     0.0,      1.0     ]
    dist_coeffs: [0.4209968759, 0.1761684490, -0.109572017, -0.970520784]  # KB model (k1 k2 k3 k4)

# Calibration Parameters.!
calib:
    calib_config_file: "/home/felix/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
